// modules
const url = require('url')
// search for link url and returns the favicon for link
exports.get = function (link) {
    const parse = url.parse(link, true)
    switch (true) {
        case parse.hostname.includes("500px.com"):
            return "500px"
        case parse.hostname.includes("app.net"):
            return "adn"
        case parse.hostname.includes("amazon.com"):
            return "amazon"
        case parse.hostname.includes("andriod.com"):
            return "android"
        case parse.hostname.includes("angel.co"):
            return "angellist"
        case parse.hostname.includes("apple.com"):
            return "apple"
        case parse.hostname.includes("archive.org"):
            return "archive-org"
        case parse.hostname.includes("artstation.com"):
            return "artstation"
        case parse.hostname.includes("att.com"):
            return "att"
        case parse.hostname.includes("bandcamp.com"):
            return "bandcamp"
        case parse.hostname.includes("behance.net"):
            return "behance"
        case parse.hostname.includes("bitbucket.org"):
            return "bitbucket"
        case parse.hostname.includes("blacktie.io"):
            return "black-tie"
        case parse.hostname.includes("boardgamegeek.com"):
            return "boardgamegeek"
        case parse.hostname.includes("buymeacoffee.com"):
            return "buymeacoffee"
        case parse.hostname.includes("buysellads.com"):
            return "buysellads"
        case parse.hostname.includes("classicpress.net"):
            return "classicpress"
        case parse.hostname.includes("codepen.io"):
            return "codepen"
        case parse.hostname.includes("codiepie.com"):
            return "codiepie"
        case parse.hostname.includes("connectdevelop.com"):
            return "connectdevelop"
        case parse.hostname.includes("contao.org"):
            return "contao"
        case parse.hostname.includes("conwaylife.com"):
            return "conway-glider"
        case parse.hostname.includes("dashcube.com"):
            return "dashcube"
        case parse.hostname.includes("delicious.com"):
            return "delicious"
        case parse.hostname.includes("dev.to"):
            return "dev-to"
        case parse.hostname.includes("deviantart.com"):
            return "deviantart"
        case parse.hostname.includes("diasporafoundation.org"):
            return "diaspora"
        case parse.hostname.includes("digg.com"):
            return "digg"
        case parse.hostname.includes("digitalocean.com"):
            return "digitalocean"
        case parse.hostname.includes("discord.com"):
            return "discord"
        case parse.hostname.includes("dogmazic.net"):
            return "dogmazic"
        case parse.hostname.includes("dribbble.com"):
            return "dribbble"
        case parse.hostname.includes("dropbox.com"):
            return "dropbox"
        case parse.hostname.includes("drupal.org"):
            return "drupal"
        case parse.hostname.includes("eercast.com"):
            return "eercast"
        case parse.hostname.includes("emby.media"):
            return "emby"
        case parse.hostname.includes("enviragallery.com"):
            return "envira"
        case parse.hostname.includes("etsy.com"):
            return "etsy"
        case parse.hostname.includes("expeditedsecurity.com"):
            return "expeditedssl"
        case parse.hostname.includes("f-droid.org"):
            return "f-droid"
        case parse.hostname.includes("facebook.com"):
            return "facebook"
        case parse.hostname.includes("messenger.com"):
            return "facebook-messenger"
        case parse.hostname.includes("flickr.com"):
            return "flickr"
        case parse.hostname.includes("forumbee.com"):
            return "forumbee"
        case parse.hostname.includes("foursquare.com"):
            return "foursquare"
        case parse.hostname.includes("freecodecamp.org"):
            return "free-code-camp"
        case parse.hostname.includes("freedombox.org"):
            return "freedombox"
        case parse.hostname.includes("friendi.ca"):
            return "friendica"
        case parse.hostname.includes("funkwhale.audio"):
            return "funkwhale"
        case parse.hostname.includes("getpocket.com"):
            return "get-pocket"
        case parse.hostname.includes("gimp.org"):
            return "gimp"
        case parse.hostname.includes("gitea.io"):
            return "gitea"
        case parse.hostname.includes("github.com"):
            return "github"
        case parse.hostname.includes("gitlab.com"):
            return "gitlab"
        case parse.hostname.includes("glide.me"):
            return "glide-g"
        case parse.hostname.includes("gnu.org"):
            return "gnu"
        case parse.hostname.includes("gnusocial.network"):
            return "gnu-social"
        case parse.hostname.includes("gnupg.org"):
            return "gnupg"
        case parse.hostname.includes("google.com"):
            switch (true) {
                case parse.hostname.includes('play'):
                    return "google-play"
                case parse.hostname.includes('plus'):
                    return "google-plus"
                default:
                    return "google"
            }
        case parse.hostname.includes("google.wallet"):
            return "google-wallet"
        case parse.hostname.includes("gratipay.com"):
            return "gratipay"
        case parse.hostname.includes("grav.com"):
            return "grav"
        case parse.hostname.includes("hackaday.com"):
            return "hackaday"
        case parse.hostname.includes("hackster.io"):
            return "hackster"
        case parse.hostname.includes("hal.archives-ouvertes.fr"):
            return "hal"
        case parse.hostname.includes("hashnode.com"):
            return "hashnode"
        case parse.hostname.includes("heroku.com"):
            return "heroku"
        case parse.hostname.includes("home-assistant.io"):
            return "home-assistant"
        case parse.hostname.includes("houzz.com"):
            return "houzz"
        case parse.hostname.includes("hubzilla.org"):
            return "hubzilla"
        case parse.hostname.includes("imdb.com"):
            return "imdb"
        case parse.hostname.includes("inkscape.org"):
            return "inkscape"
        case parse.hostname.includes("instagram.com"):
            return "instagram"
        case parse.hostname.includes("iox.host"):
            return "ioxhost"
        case parse.hostname.includes("jirafeau.net"):
            return "jirafeau"
        case parse.hostname.includes("joomla.org"):
            return "joomla"
        case parse.hostname.includes("joplinapp.org"):
            return "joplin"
        case parse.hostname.includes("jsfiddle.net"):
            return "jsfiddle"
        case parse.hostname.includes("julialang.org"):
            return "julia"
        case parse.hostname.includes("jupyter.org"):
            return "jupyter"
        case parse.hostname.includes("keybase.io"):
            return "keybase"
        case parse.hostname.includes("last.fm"):
            return "lastfm"
        case parse.hostname.includes("leanpub.com"):
            return "leanpub"
        case parse.hostname.includes("liberapay.com"):
            return "liberapay"
        case parse.hostname.includes("linkedin.com"):
            return "linkedin"
        case parse.hostname.includes("linode.com"):
            return "linode"
        case parse.hostname.includes("joinmastodon.org"):
            return "mastodon"
        case parse.hostname.includes("matrix.org"):
            return "matrix-org"
        case parse.hostname.includes("stackpath.com"):
            return "maxcdn"
        case parse.hostname.includes("medium.com"):
            return "medium"
        case parse.hostname.includes("meetup.com"):
            return "meetup"
        case parse.hostname.includes("mixcloud.com"):
            return "mixcloud"
        case parse.hostname.includes("modx.com"):
            return "modx"
        case parse.hostname.includes("nextcloud.com"):
            return "nextcloud"
        case parse.hostname.includes("ok.ru"):
            return "odnoklassniki"
        case parse.hostname.includes("opencollective.com"):
            return "open-collective"
        case parse.hostname.includes("opencart.com"):
            return "opencart"
        case parse.hostname.includes("openid.net"):
            return "openid"
        case parse.hostname.includes("optinmonster.com"):
            return "optin-monster"
        case parse.hostname.includes("orcid.org"):
            return "orcid"
        case parse.hostname.includes("pagelines.com"):
            return "pagelines"
        case parse.hostname.includes("patreon.com"):
            return "patreon"
        case parse.hostname.includes("paypal.com"):
            return "paypal"
        case parse.hostname.includes("joinpeertube.org"):
            return "peertube"
        case parse.hostname.includes("pinterest.com"):
            return "pinterest-p"
        case parse.hostname.includes("pixelfed.org"):
            return "pixelfed"
        case parse.hostname.includes("pleroma.social"):
            return "pleroma"
        case parse.hostname.includes("joinplu.me"):
            return "plume"
        case parse.hostname.includes("producthunt.com"):
            return "product-hunt"
        case parse.hostname.includes("im.qq.com"):
            return "qq"
        case parse.hostname.includes("quora.com"):
            return "quora"
        case parse.hostname.includes("ravelry.com"):
            return "ravelry"
        case parse.hostname.includes("reddit.com"):
            return "reddit-alien"
        case parse.hostname.includes("renren.com"):
            return "renren"
        case parse.hostname.includes("researchgate.net"):
            return "researchgate"
        case parse.hostname.includes("scribd.com"):
            return "scribd"
        case parse.hostname.includes("scuttlebutt.nz"):
            return "scuttlebutt"
        case parse.hostname.includes("sellsy.com"):
            return "sellsy"
        case parse.hostname.includes("shaarli.org"):
            return "shaarli"
        case parse.hostname.includes("shirtsinbulk.com"):
            return "shirtsinbulk"
        case parse.hostname.includes("sketchfab.com"):
            return "sketchfab"
        case parse.hostname.includes("skyatlas.com"):
            return "skyatlas"
        case parse.hostname.includes("skype.com"):
            return "skype"
        case parse.hostname.includes("slack.com"):
            return "slack"
        case parse.hostname.includes("slideshare.net"):
            return "slideshare"
        case parse.hostname.includes("snapchat.com"):
            return "snapchat-ghost"
        case parse.hostname.includes("socialhome.network"):
            return "social-home"
        case parse.hostname.includes("soundcloud.com"):
            return "soundcloud"
        case parse.hostname.includes("spotify.com"):
            return "spotify"
        case parse.hostname.includes("stackexchange.com"):
            return "stack-exchange"
        case parse.hostname.includes("stackoverflow.com"):
            return "stack-overflow"
        case parse.hostname.includes("store.steampowered.com"):
            return "steam"
        case parse.hostname.includes("stumbleupon.com"):
            return "stumbleupon"
        case parse.hostname.includes("syncthing.net"):
            return "syncthing"
        case parse.hostname.includes("telegram.org"):
            return "telegram"
        case parse.hostname.includes("weibo.com"):
            return "tencent-weibo"
        case parse.hostname.includes("tug.org"):
            return "tex"
        case parse.hostname.includes("textpattern.com"):
            return "textpattern"
        case parse.hostname.includes("themeisle.com"):
            return "themeisle"
        case parse.hostname.includes("tipeee.com"):
            return "tipeee"
        case parse.hostname.includes(".onion"):
            return "tor-onion"
        case parse.hostname.includes("trello.com"):
            return "trello"
        case parse.hostname.includes("tripadvisor.com"):
            return "tripadvisor"
        case parse.hostname.includes("tumblr.com"):
            return "tumblr"
        case parse.hostname.includes("twitch.tv"):
            return "twitch"
        case parse.hostname.includes("twitter.com"):
            return "twitter"
        case parse.hostname.includes("unity.com"):
            return "unity"
        case parse.hostname.includes("unsplash.com"):
            return "unsplash"
        case parse.hostname.includes("viadeo.com"):
            return "viadeo"
        case parse.hostname.includes("vimeo.com"):
            return "vimeo"
        case parse.hostname.includes("vk.com"):
            return "vk"
        case parse.hostname.includes("weibo.com"):
            return "weibo"
        case parse.hostname.includes("wechat.com"):
            return "weixin"
        case parse.hostname.includes("whatsapp.com"):
            return "whatsapp"
        case parse.hostname.includes("wikidata.org"):
            return "wikidata"
        case parse.hostname.includes("wikipedia.org"):
            return "wikipedia-w"
        case parse.hostname.includes("wire.com"):
            return "wire"
        case parse.hostname.includes("wordpress.org"):
            return "wordpress"
        case parse.hostname.includes("wpbeginner.com"):
            return "wpbeginner"
        case parse.hostname.includes("wpexplorer.com"):
            return "wpexplorer"
        case parse.hostname.includes("wpforms.com"):
            return "wpforms"
        case parse.hostname.includes("xing.com"):
            return "xing"
        case parse.hostname.includes("xmpp.org"):
            return "xmpp"
        case parse.hostname.includes("ycombinator.com"):
            switch (true) {
                case parse.hostname.includes("news"):
                    return "hacker-news"
                default:
                    return "y-combinator"
            }
        case parse.hostname.includes("yahoo.com"):
            return "yahoo"
        case parse.hostname.includes("yelp.com"):
            return "yelp"
        case parse.hostname.includes("yoast.com"):
            return "yoast"
        case parse.hostname.includes("youtube.com"):
            return "youtube-play"
        case parse.hostname.includes("zotero.org"):
            return "zotero"
        default:
            return "link"
    }
}